# Generated by Django 6.0.3 on 2026-04-03 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_certificate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='cert_type',
            field=models.CharField(choices=[('civic_spark', 'Civic Spark Recognition (50+ Points)'), ('active_citizen', 'Active Citizen Award'), ('city_contributor', 'City Contributor Certificate')], max_length=32),
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('resolved', 'Issue resolved'), ('points', 'Points milestone'), ('verified', 'Issue verified'), ('system', 'System')], default='system', max_length=16)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('read', models.BooleanField(default=False)),
                ('issue_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='civic_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
