# Generated by Django 6.0.3 on 2026-04-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_issue_verification_and_counts'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='before_img_captured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='image_exif_note',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='issue',
            name='image_exif_suspicious',
            field=models.BooleanField(default=False),
        ),
    ]
