# Generated by Django 5.0.6 on 2026-04-02 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='is_duplicate',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='issue',
            name='after_img',
            field=models.ImageField(blank=True, null=True, upload_to='issues/'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='before_img',
            field=models.ImageField(blank=True, null=True, upload_to='issues/'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
